
package cn.com.webxml;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.4
 * 2024-06-28T21:08:54.658+08:00
 * Generated source version: 4.0.4
 *
 */
public final class IpAddressSearchWebServiceSoap_IpAddressSearchWebServiceSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://WebXml.com.cn/", "IpAddressSearchWebService");

    private IpAddressSearchWebServiceSoap_IpAddressSearchWebServiceSoap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = IpAddressSearchWebService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        IpAddressSearchWebService ss = new IpAddressSearchWebService(wsdlURL, SERVICE_NAME);
        IpAddressSearchWebServiceSoap port = ss.getIpAddressSearchWebServiceSoap12();

        {
        System.out.println("Invoking getCountryCityByIp...");
        java.lang.String _getCountryCityByIp_theIpAddress = "";
        cn.com.webxml.ArrayOfString _getCountryCityByIp__return = port.getCountryCityByIp(_getCountryCityByIp_theIpAddress);
        System.out.println("getCountryCityByIp.result=" + _getCountryCityByIp__return);


        }
        {
        System.out.println("Invoking getGeoIPContext...");
        cn.com.webxml.ArrayOfString _getGeoIPContext__return = port.getGeoIPContext();
        System.out.println("getGeoIPContext.result=" + _getGeoIPContext__return);


        }
        {
        System.out.println("Invoking getVersionTime...");
        java.lang.String _getVersionTime__return = port.getVersionTime();
        System.out.println("getVersionTime.result=" + _getVersionTime__return);


        }

        System.exit(0);
    }

}
