package com.shingle.cxf.client;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.4
 * 2024-06-29T10:32:06.706+08:00
 * Generated source version: 4.0.4
 *
 */
@WebService(targetNamespace = "http://service.cxf.shingle.com/", name = "UserService")
@XmlSeeAlso({ObjectFactory.class})
public interface UserService {

    @WebMethod
    @RequestWrapper(localName = "getUserById", targetNamespace = "http://service.cxf.shingle.com/", className = "com.shingle.cxf.client.GetUserById")
    @ResponseWrapper(localName = "getUserByIdResponse", targetNamespace = "http://service.cxf.shingle.com/", className = "com.shingle.cxf.client.GetUserByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.shingle.cxf.client.UserBo getUserById(

        @WebParam(name = "id", targetNamespace = "")
        java.lang.Long id
    );

    @WebMethod
    @RequestWrapper(localName = "queryUserByParam", targetNamespace = "http://service.cxf.shingle.com/", className = "com.shingle.cxf.client.QueryUserByParam")
    @ResponseWrapper(localName = "queryUserByParamResponse", targetNamespace = "http://service.cxf.shingle.com/", className = "com.shingle.cxf.client.QueryUserByParamResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.shingle.cxf.client.UserBo queryUserByParam(

        @WebParam(name = "param", targetNamespace = "")
        com.shingle.cxf.client.UserQueryParam param
    );
}
